//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace job_portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_table
    {
        public int job_id { get; set; }
        public int company_id { get; set; }
        public string job_title { get; set; }
        public string job_location { get; set; }
        public int experience_in_years { get; set; }
        public string job_skills { get; set; }
        public string job_qualification { get; set; }
        public int passout_year { get; set; }
        public string job_status { get; set; }
        public System.DateTime date { get; set; }
        public System.DateTime end_date { get; set; }
        public string job_description { get; set; }
        public string job_type { get; set; }
    }
}
