//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace job_portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobapplication_table
    {
        public int application_id { get; set; }
        public int user_id { get; set; }
        public int job_id { get; set; }
        public System.DateTime application_date { get; set; }
        public string resume { get; set; }
        public string application_status { get; set; }
    }
}
