//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace job_portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class login_table
    {
        public int login_id { get; set; }
        public int reg_id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string login_type { get; set; }
    }
}
