//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace job_portal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class jobportal_mvcEntities : DbContext
    {
        public jobportal_mvcEntities()
            : base("name=jobportal_mvcEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<company_table> company_table { get; set; }
        public virtual DbSet<job_table> job_table { get; set; }
        public virtual DbSet<jobapplication_table> jobapplication_table { get; set; }
        public virtual DbSet<login_table> login_table { get; set; }
        public virtual DbSet<user_table> user_table { get; set; }
    
        public virtual ObjectResult<Nullable<int>> sp_countregid(string email, string pswd)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var pswdParameter = pswd != null ?
                new ObjectParameter("pswd", pswd) :
                new ObjectParameter("pswd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_countregid", emailParameter, pswdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_emailcheck(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_emailcheck", emailParameter);
        }
    
        public virtual int sp_insertcmpny(Nullable<int> id, string na, string desc, string pho, string addr, string locatn)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var naParameter = na != null ?
                new ObjectParameter("na", na) :
                new ObjectParameter("na", typeof(string));
    
            var descParameter = desc != null ?
                new ObjectParameter("desc", desc) :
                new ObjectParameter("desc", typeof(string));
    
            var phoParameter = pho != null ?
                new ObjectParameter("pho", pho) :
                new ObjectParameter("pho", typeof(string));
    
            var addrParameter = addr != null ?
                new ObjectParameter("addr", addr) :
                new ObjectParameter("addr", typeof(string));
    
            var locatnParameter = locatn != null ?
                new ObjectParameter("locatn", locatn) :
                new ObjectParameter("locatn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insertcmpny", idParameter, naParameter, descParameter, phoParameter, addrParameter, locatnParameter);
        }
    
        public virtual int sp_insertusr(Nullable<int> id, string na, string pho, string gend, Nullable<int> ag, string addr, string quali, Nullable<int> exp, string skil, string sts)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var naParameter = na != null ?
                new ObjectParameter("na", na) :
                new ObjectParameter("na", typeof(string));
    
            var phoParameter = pho != null ?
                new ObjectParameter("pho", pho) :
                new ObjectParameter("pho", typeof(string));
    
            var gendParameter = gend != null ?
                new ObjectParameter("gend", gend) :
                new ObjectParameter("gend", typeof(string));
    
            var agParameter = ag.HasValue ?
                new ObjectParameter("ag", ag) :
                new ObjectParameter("ag", typeof(int));
    
            var addrParameter = addr != null ?
                new ObjectParameter("addr", addr) :
                new ObjectParameter("addr", typeof(string));
    
            var qualiParameter = quali != null ?
                new ObjectParameter("quali", quali) :
                new ObjectParameter("quali", typeof(string));
    
            var expParameter = exp.HasValue ?
                new ObjectParameter("exp", exp) :
                new ObjectParameter("exp", typeof(int));
    
            var skilParameter = skil != null ?
                new ObjectParameter("skil", skil) :
                new ObjectParameter("skil", typeof(string));
    
            var stsParameter = sts != null ?
                new ObjectParameter("sts", sts) :
                new ObjectParameter("sts", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insertusr", idParameter, naParameter, phoParameter, gendParameter, agParameter, addrParameter, qualiParameter, expParameter, skilParameter, stsParameter);
        }
    
        public virtual int sp_logininsert(Nullable<int> reg, string email, string pswd, string logtype)
        {
            var regParameter = reg.HasValue ?
                new ObjectParameter("reg", reg) :
                new ObjectParameter("reg", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var pswdParameter = pswd != null ?
                new ObjectParameter("pswd", pswd) :
                new ObjectParameter("pswd", typeof(string));
    
            var logtypeParameter = logtype != null ?
                new ObjectParameter("logtype", logtype) :
                new ObjectParameter("logtype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_logininsert", regParameter, emailParameter, pswdParameter, logtypeParameter);
        }
    
        public virtual ObjectResult<string> sp_logintype(string email, string pswd)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var pswdParameter = pswd != null ?
                new ObjectParameter("pswd", pswd) :
                new ObjectParameter("pswd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_logintype", emailParameter, pswdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_regidcount()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_regidcount");
        }
    
        public virtual ObjectResult<Nullable<int>> sp_regidselect(string email, string pswd)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var pswdParameter = pswd != null ?
                new ObjectParameter("pswd", pswd) :
                new ObjectParameter("pswd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_regidselect", emailParameter, pswdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_emailcount(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_emailcount", emailParameter);
        }
    
        public virtual int sp_insertjobpost(Nullable<int> cmpnyid, string jobtitle, string loc, Nullable<int> exp, string skill, string qual, Nullable<int> passyr, string jobsts, Nullable<System.DateTime> strtdate, Nullable<System.DateTime> enddate, string desc, string jobtype, string jobsalary)
        {
            var cmpnyidParameter = cmpnyid.HasValue ?
                new ObjectParameter("cmpnyid", cmpnyid) :
                new ObjectParameter("cmpnyid", typeof(int));
    
            var jobtitleParameter = jobtitle != null ?
                new ObjectParameter("jobtitle", jobtitle) :
                new ObjectParameter("jobtitle", typeof(string));
    
            var locParameter = loc != null ?
                new ObjectParameter("loc", loc) :
                new ObjectParameter("loc", typeof(string));
    
            var expParameter = exp.HasValue ?
                new ObjectParameter("exp", exp) :
                new ObjectParameter("exp", typeof(int));
    
            var skillParameter = skill != null ?
                new ObjectParameter("skill", skill) :
                new ObjectParameter("skill", typeof(string));
    
            var qualParameter = qual != null ?
                new ObjectParameter("qual", qual) :
                new ObjectParameter("qual", typeof(string));
    
            var passyrParameter = passyr.HasValue ?
                new ObjectParameter("passyr", passyr) :
                new ObjectParameter("passyr", typeof(int));
    
            var jobstsParameter = jobsts != null ?
                new ObjectParameter("jobsts", jobsts) :
                new ObjectParameter("jobsts", typeof(string));
    
            var strtdateParameter = strtdate.HasValue ?
                new ObjectParameter("strtdate", strtdate) :
                new ObjectParameter("strtdate", typeof(System.DateTime));
    
            var enddateParameter = enddate.HasValue ?
                new ObjectParameter("enddate", enddate) :
                new ObjectParameter("enddate", typeof(System.DateTime));
    
            var descParameter = desc != null ?
                new ObjectParameter("desc", desc) :
                new ObjectParameter("desc", typeof(string));
    
            var jobtypeParameter = jobtype != null ?
                new ObjectParameter("jobtype", jobtype) :
                new ObjectParameter("jobtype", typeof(string));
    
            var jobsalaryParameter = jobsalary != null ?
                new ObjectParameter("jobsalary", jobsalary) :
                new ObjectParameter("jobsalary", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insertjobpost", cmpnyidParameter, jobtitleParameter, locParameter, expParameter, skillParameter, qualParameter, passyrParameter, jobstsParameter, strtdateParameter, enddateParameter, descParameter, jobtypeParameter, jobsalaryParameter);
        }
    
        public virtual ObjectResult<sp_displayalljobs_Result> sp_displayalljobs()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_displayalljobs_Result>("sp_displayalljobs");
        }
    
        public virtual int sp_jobsearch(string qry)
        {
            var qryParameter = qry != null ?
                new ObjectParameter("qry", qry) :
                new ObjectParameter("qry", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_jobsearch", qryParameter);
        }
    
        public virtual ObjectResult<sp_alljobdisplay_Result> sp_alljobdisplay()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_alljobdisplay_Result>("sp_alljobdisplay");
        }
    }
}
