//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace job_portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_table
    {
        public int user_id { get; set; }
        public string user_name { get; set; }
        public string user_phone { get; set; }
        public string gender { get; set; }
        public int age { get; set; }
        public string user_address { get; set; }
        public string qualification { get; set; }
        public int experience { get; set; }
        public string skills { get; set; }
        public string user_status { get; set; }
    }
}
